26/07/2020 21:36:00  Warnungen: 
26/07/2020 21:36:00   * Running on http://127.0.0.1:1337/ (Press CTRL+C to quit)
26/07/2020 21:36:00   * Restarting with stat
26/07/2020 21:36:00  Warnungen: 
26/07/2020 21:36:00   * Debugger is active!
26/07/2020 21:36:00   * Debugger PIN: 376-230-688
26/07/2020 21:50:05   * Detected change in '/home/aboro72/PycharmProjects/flask-pos/app/routes.py', reloading
26/07/2020 21:50:05   * Restarting with stat
26/07/2020 21:50:06  Warnungen: 
26/07/2020 21:50:06   * Debugger is active!
26/07/2020 21:50:06   * Debugger PIN: 376-230-688
26/07/2020 21:51:37  127.0.0.1 - - [26/Jul/2020 21:51:37] "[35m[1mGET / HTTP/1.1[0m" 500 -
26/07/2020 21:51:37  127.0.0.1 - - [26/Jul/2020 21:51:37] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
26/07/2020 21:51:37  127.0.0.1 - - [26/Jul/2020 21:51:37] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
26/07/2020 21:51:37  127.0.0.1 - - [26/Jul/2020 21:51:37] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
26/07/2020 21:51:38  127.0.0.1 - - [26/Jul/2020 21:51:38] "[37mGET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
26/07/2020 21:51:38  127.0.0.1 - - [26/Jul/2020 21:51:38] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 21:51:38  127.0.0.1 - - [26/Jul/2020 21:51:38] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 21:51:55  127.0.0.1 - - [26/Jul/2020 21:51:55] "[35m[1mGET /index HTTP/1.1[0m" 500 -
26/07/2020 21:51:56  127.0.0.1 - - [26/Jul/2020 21:51:56] "[37mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
26/07/2020 21:51:56  127.0.0.1 - - [26/Jul/2020 21:51:56] "[37mGET /index?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
26/07/2020 21:51:56  127.0.0.1 - - [26/Jul/2020 21:51:56] "[37mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
26/07/2020 21:51:56  127.0.0.1 - - [26/Jul/2020 21:51:56] "[37mGET /index?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
26/07/2020 21:51:56  127.0.0.1 - - [26/Jul/2020 21:51:56] "[37mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 21:53:00  Warnungen: 
26/07/2020 21:53:00   * Running on http://127.0.0.1:1337/ (Press CTRL+C to quit)
26/07/2020 21:53:00   * Restarting with stat
26/07/2020 21:53:00  Warnungen: 
26/07/2020 21:53:00   * Debugger is active!
26/07/2020 21:53:00   * Debugger PIN: 376-230-688
26/07/2020 21:53:04  127.0.0.1 - - [26/Jul/2020 21:53:04] "[37mGET /index HTTP/1.1[0m" 200 -
26/07/2020 21:53:05  127.0.0.1 - - [26/Jul/2020 21:53:05] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
26/07/2020 21:57:12  127.0.0.1 - - [26/Jul/2020 21:57:12] "[37mGET /index HTTP/1.1[0m" 200 -
26/07/2020 21:58:24  127.0.0.1 - - [26/Jul/2020 21:58:24] "[37mGET /index HTTP/1.1[0m" 200 -
26/07/2020 22:11:32  127.0.0.1 - - [26/Jul/2020 22:11:32] "[37mGET /index HTTP/1.1[0m" 200 -
26/07/2020 22:11:32  127.0.0.1 - - [26/Jul/2020 22:11:32] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
26/07/2020 22:11:34  127.0.0.1 - - [26/Jul/2020 22:11:34] "[37mGET /index HTTP/1.1[0m" 200 -
26/07/2020 22:11:34  127.0.0.1 - - [26/Jul/2020 22:11:34] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
26/07/2020 22:14:15   * Detected change in '/home/aboro72/PycharmProjects/flask-pos/app/routes.py', reloading
26/07/2020 22:14:15   * Restarting with stat
26/07/2020 22:14:16  Warnungen: 
26/07/2020 22:14:16   * Debugger is active!
26/07/2020 22:14:16   * Debugger PIN: 376-230-688
26/07/2020 22:14:17  127.0.0.1 - - [26/Jul/2020 22:14:17] "[37mGET /index HTTP/1.1[0m" 200 -
26/07/2020 22:14:18  127.0.0.1 - - [26/Jul/2020 22:14:18] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
26/07/2020 22:16:03  127.0.0.1 - - [26/Jul/2020 22:16:03] "[37mGET /index HTTP/1.1[0m" 200 -
26/07/2020 22:16:03  127.0.0.1 - - [26/Jul/2020 22:16:03] "[33mGET /dist/css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:16:03  127.0.0.1 - - [26/Jul/2020 22:16:03] "[33mGET /sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:16:03  127.0.0.1 - - [26/Jul/2020 22:16:03] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
26/07/2020 22:16:25  127.0.0.1 - - [26/Jul/2020 22:16:25] "[37mGET /index HTTP/1.1[0m" 200 -
26/07/2020 22:16:25  127.0.0.1 - - [26/Jul/2020 22:16:25] "[33mGET /dist/css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:16:25  127.0.0.1 - - [26/Jul/2020 22:16:25] "[33mGET /sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:16:30  127.0.0.1 - - [26/Jul/2020 22:16:30] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:16:30  127.0.0.1 - - [26/Jul/2020 22:16:30] "[33mGET /dist/css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:16:30  127.0.0.1 - - [26/Jul/2020 22:16:30] "[33mGET /sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:20:06  127.0.0.1 - - [26/Jul/2020 22:20:06] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:20:07  127.0.0.1 - - [26/Jul/2020 22:20:07] "[37mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 200 -
26/07/2020 22:20:07  127.0.0.1 - - [26/Jul/2020 22:20:07] "[33mGET /static/css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:20:08  127.0.0.1 - - [26/Jul/2020 22:20:08] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:20:08  127.0.0.1 - - [26/Jul/2020 22:20:08] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:20:08  127.0.0.1 - - [26/Jul/2020 22:20:08] "[33mGET /static/css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:20:09  127.0.0.1 - - [26/Jul/2020 22:20:09] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:20:10  127.0.0.1 - - [26/Jul/2020 22:20:10] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:20:10  127.0.0.1 - - [26/Jul/2020 22:20:10] "[33mGET /static/css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:20:13  127.0.0.1 - - [26/Jul/2020 22:20:13] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:20:13  127.0.0.1 - - [26/Jul/2020 22:20:13] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:20:13  127.0.0.1 - - [26/Jul/2020 22:20:13] "[33mGET /static/css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:20:14  127.0.0.1 - - [26/Jul/2020 22:20:14] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:20:14  127.0.0.1 - - [26/Jul/2020 22:20:14] "[33mGET /static/css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:20:14  127.0.0.1 - - [26/Jul/2020 22:20:14] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:20:15  127.0.0.1 - - [26/Jul/2020 22:20:15] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:20:15  127.0.0.1 - - [26/Jul/2020 22:20:15] "[33mGET /static/css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:20:15  127.0.0.1 - - [26/Jul/2020 22:20:15] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:21:35  127.0.0.1 - - [26/Jul/2020 22:21:35] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:21:35  127.0.0.1 - - [26/Jul/2020 22:21:35] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:21:35  127.0.0.1 - - [26/Jul/2020 22:21:35] "[33mGET /css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:21:36  127.0.0.1 - - [26/Jul/2020 22:21:36] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:21:36  127.0.0.1 - - [26/Jul/2020 22:21:36] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:21:36  127.0.0.1 - - [26/Jul/2020 22:21:36] "[33mGET /css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:21:38  127.0.0.1 - - [26/Jul/2020 22:21:38] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:21:38  127.0.0.1 - - [26/Jul/2020 22:21:38] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:21:38  127.0.0.1 - - [26/Jul/2020 22:21:38] "[33mGET /css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:26:20  127.0.0.1 - - [26/Jul/2020 22:26:20] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:26:20  127.0.0.1 - - [26/Jul/2020 22:26:20] "[33mGET /css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:26:20  127.0.0.1 - - [26/Jul/2020 22:26:20] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:28:44  127.0.0.1 - - [26/Jul/2020 22:28:44] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:28:44  127.0.0.1 - - [26/Jul/2020 22:28:44] "[33mGET /css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:28:44  127.0.0.1 - - [26/Jul/2020 22:28:44] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:28:57  Warnungen: 
26/07/2020 22:28:57   * Running on http://127.0.0.1:1337/ (Press CTRL+C to quit)
26/07/2020 22:28:57   * Restarting with stat
26/07/2020 22:28:57  Warnungen: 
26/07/2020 22:28:57   * Debugger is active!
26/07/2020 22:28:58   * Debugger PIN: 376-230-688
26/07/2020 22:30:15   * Detected change in '/home/aboro72/PycharmProjects/flask-pos/app/routes.py', reloading
26/07/2020 22:30:15   * Restarting with stat
26/07/2020 22:30:16  Warnungen: 
26/07/2020 22:30:16   * Debugger is active!
26/07/2020 22:30:16   * Debugger PIN: 376-230-688
26/07/2020 22:30:18  127.0.0.1 - - [26/Jul/2020 22:30:18] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:30:19  127.0.0.1 - - [26/Jul/2020 22:30:19] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:30:19  127.0.0.1 - - [26/Jul/2020 22:30:19] "[33mGET /css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:31:50  127.0.0.1 - - [26/Jul/2020 22:31:50] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:31:50  127.0.0.1 - - [26/Jul/2020 22:31:50] "[33mGET /css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:31:50  127.0.0.1 - - [26/Jul/2020 22:31:50] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:31:51  127.0.0.1 - - [26/Jul/2020 22:31:51] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:31:52  127.0.0.1 - - [26/Jul/2020 22:31:52] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:31:52  127.0.0.1 - - [26/Jul/2020 22:31:52] "[33mGET /css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:33:53  127.0.0.1 - - [26/Jul/2020 22:33:53] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:33:54  127.0.0.1 - - [26/Jul/2020 22:33:54] "[33mGET /css/sticky-footer-navbar.css HTTP/1.1[0m" 404 -
26/07/2020 22:33:54  127.0.0.1 - - [26/Jul/2020 22:33:54] "[36mGET /static/css/bootstrap.min.css HTTP/1.1[0m" 304 -
26/07/2020 22:35:26  127.0.0.1 - - [26/Jul/2020 22:35:26] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:35:26  127.0.0.1 - - [26/Jul/2020 22:35:26] "[33mGET /cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:35:26  127.0.0.1 - - [26/Jul/2020 22:35:26] "[33mGET /dist/css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:37:08  127.0.0.1 - - [26/Jul/2020 22:37:08] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:37:08  127.0.0.1 - - [26/Jul/2020 22:37:08] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:37:08  127.0.0.1 - - [26/Jul/2020 22:37:08] "[33mGET /cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:37:09  127.0.0.1 - - [26/Jul/2020 22:37:09] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:37:09  127.0.0.1 - - [26/Jul/2020 22:37:09] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:37:09  127.0.0.1 - - [26/Jul/2020 22:37:09] "[33mGET /cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:37:10  127.0.0.1 - - [26/Jul/2020 22:37:10] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:37:11  127.0.0.1 - - [26/Jul/2020 22:37:11] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:37:11  127.0.0.1 - - [26/Jul/2020 22:37:11] "[33mGET /cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:38:37  127.0.0.1 - - [26/Jul/2020 22:38:37] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:38:37  127.0.0.1 - - [26/Jul/2020 22:38:37] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:38:37  127.0.0.1 - - [26/Jul/2020 22:38:37] "[33mGET /cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:25  127.0.0.1 - - [26/Jul/2020 22:39:25] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:39:25  127.0.0.1 - - [26/Jul/2020 22:39:25] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:25  127.0.0.1 - - [26/Jul/2020 22:39:25] "[33mGET /cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:26  127.0.0.1 - - [26/Jul/2020 22:39:26] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:39:26  127.0.0.1 - - [26/Jul/2020 22:39:26] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:26  127.0.0.1 - - [26/Jul/2020 22:39:26] "[33mGET /cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:28  127.0.0.1 - - [26/Jul/2020 22:39:28] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:39:28  127.0.0.1 - - [26/Jul/2020 22:39:28] "[33mGET /cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:28  127.0.0.1 - - [26/Jul/2020 22:39:28] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:55  127.0.0.1 - - [26/Jul/2020 22:39:55] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:39:55  127.0.0.1 - - [26/Jul/2020 22:39:55] "[33mGET /css/cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:55  127.0.0.1 - - [26/Jul/2020 22:39:55] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:56  127.0.0.1 - - [26/Jul/2020 22:39:56] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:39:57  127.0.0.1 - - [26/Jul/2020 22:39:57] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:57  127.0.0.1 - - [26/Jul/2020 22:39:57] "[33mGET /css/cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:58  127.0.0.1 - - [26/Jul/2020 22:39:58] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:39:58  127.0.0.1 - - [26/Jul/2020 22:39:58] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:58  127.0.0.1 - - [26/Jul/2020 22:39:58] "[33mGET /css/cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:59  127.0.0.1 - - [26/Jul/2020 22:39:59] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:39:59  127.0.0.1 - - [26/Jul/2020 22:39:59] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:39:59  127.0.0.1 - - [26/Jul/2020 22:39:59] "[33mGET /css/cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:40:02  127.0.0.1 - - [26/Jul/2020 22:40:02] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:40:02  127.0.0.1 - - [26/Jul/2020 22:40:02] "[33mGET /css/cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:40:02  127.0.0.1 - - [26/Jul/2020 22:40:02] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:40:03  127.0.0.1 - - [26/Jul/2020 22:40:03] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:40:03  127.0.0.1 - - [26/Jul/2020 22:40:03] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:40:03  127.0.0.1 - - [26/Jul/2020 22:40:03] "[33mGET /css/cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:40:21  127.0.0.1 - - [26/Jul/2020 22:40:21] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:40:21  127.0.0.1 - - [26/Jul/2020 22:40:21] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:40:21  127.0.0.1 - - [26/Jul/2020 22:40:21] "[33mGET /css/cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:40:22  127.0.0.1 - - [26/Jul/2020 22:40:22] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:40:22  127.0.0.1 - - [26/Jul/2020 22:40:22] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:40:22  127.0.0.1 - - [26/Jul/2020 22:40:22] "[33mGET /css/cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:45:26  127.0.0.1 - - [26/Jul/2020 22:45:26] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:45:26  127.0.0.1 - - [26/Jul/2020 22:45:26] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:45:26  127.0.0.1 - - [26/Jul/2020 22:45:26] "[33mGET /styles/css/cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:45:28  127.0.0.1 - - [26/Jul/2020 22:45:28] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:45:28  127.0.0.1 - - [26/Jul/2020 22:45:28] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:45:28  127.0.0.1 - - [26/Jul/2020 22:45:28] "[33mGET /styles/css/cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:45:30  127.0.0.1 - - [26/Jul/2020 22:45:30] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 22:45:30  127.0.0.1 - - [26/Jul/2020 22:45:30] "[33mGET /css/bootstrap.min.css HTTP/1.1[0m" 404 -
26/07/2020 22:45:30  127.0.0.1 - - [26/Jul/2020 22:45:30] "[33mGET /styles/css/cover.css HTTP/1.1[0m" 404 -
26/07/2020 22:50:47  127.0.0.1 - - [26/Jul/2020 22:50:47] "[35m[1mGET / HTTP/1.1[0m" 500 -
26/07/2020 22:50:47  127.0.0.1 - - [26/Jul/2020 22:50:47] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
26/07/2020 22:50:47  127.0.0.1 - - [26/Jul/2020 22:50:47] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
26/07/2020 22:50:47  127.0.0.1 - - [26/Jul/2020 22:50:47] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
26/07/2020 22:50:47  127.0.0.1 - - [26/Jul/2020 22:50:47] "[37mGET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
26/07/2020 22:50:47  127.0.0.1 - - [26/Jul/2020 22:50:47] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 22:50:49  127.0.0.1 - - [26/Jul/2020 22:50:49] "[35m[1mGET / HTTP/1.1[0m" 500 -
26/07/2020 22:50:49  127.0.0.1 - - [26/Jul/2020 22:50:49] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
26/07/2020 22:50:49  127.0.0.1 - - [26/Jul/2020 22:50:49] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
26/07/2020 22:50:49  127.0.0.1 - - [26/Jul/2020 22:50:49] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
26/07/2020 22:50:49  127.0.0.1 - - [26/Jul/2020 22:50:49] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 22:50:53  127.0.0.1 - - [26/Jul/2020 22:50:53] "[35m[1mGET / HTTP/1.1[0m" 500 -
26/07/2020 22:50:54  127.0.0.1 - - [26/Jul/2020 22:50:54] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
26/07/2020 22:50:54  127.0.0.1 - - [26/Jul/2020 22:50:54] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
26/07/2020 22:50:54  127.0.0.1 - - [26/Jul/2020 22:50:54] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
26/07/2020 22:50:54  127.0.0.1 - - [26/Jul/2020 22:50:54] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 22:54:39  127.0.0.1 - - [26/Jul/2020 22:54:39] "[35m[1mGET / HTTP/1.1[0m" 500 -
26/07/2020 22:54:39  127.0.0.1 - - [26/Jul/2020 22:54:39] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
26/07/2020 22:54:39  127.0.0.1 - - [26/Jul/2020 22:54:39] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
26/07/2020 22:54:39  127.0.0.1 - - [26/Jul/2020 22:54:39] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
26/07/2020 22:54:39  127.0.0.1 - - [26/Jul/2020 22:54:39] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 22:56:10  127.0.0.1 - - [26/Jul/2020 22:56:10] "[35m[1mGET / HTTP/1.1[0m" 500 -
26/07/2020 22:56:10  127.0.0.1 - - [26/Jul/2020 22:56:10] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
26/07/2020 22:56:10  127.0.0.1 - - [26/Jul/2020 22:56:10] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
26/07/2020 22:56:10  127.0.0.1 - - [26/Jul/2020 22:56:10] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
26/07/2020 22:56:10  127.0.0.1 - - [26/Jul/2020 22:56:10] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 23:02:54  127.0.0.1 - - [26/Jul/2020 23:02:54] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:02:55  127.0.0.1 - - [26/Jul/2020 23:02:55] "[37mGET /static/styles/cover.css HTTP/1.1[0m" 200 -
26/07/2020 23:04:42  127.0.0.1 - - [26/Jul/2020 23:04:42] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:04:44  127.0.0.1 - - [26/Jul/2020 23:04:44] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:04:44  127.0.0.1 - - [26/Jul/2020 23:04:44] "[37mGET /static/styles/css/sticky-footer.css HTTP/1.1[0m" 200 -
26/07/2020 23:06:24  127.0.0.1 - - [26/Jul/2020 23:06:24] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:06:24  127.0.0.1 - - [26/Jul/2020 23:06:24] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:06:26  127.0.0.1 - - [26/Jul/2020 23:06:26] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:06:26  127.0.0.1 - - [26/Jul/2020 23:06:26] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:06:27  127.0.0.1 - - [26/Jul/2020 23:06:27] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:06:27  127.0.0.1 - - [26/Jul/2020 23:06:27] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:08:31  127.0.0.1 - - [26/Jul/2020 23:08:31] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:08:32  127.0.0.1 - - [26/Jul/2020 23:08:32] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:08:35  127.0.0.1 - - [26/Jul/2020 23:08:35] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:08:35  127.0.0.1 - - [26/Jul/2020 23:08:35] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:11:39  127.0.0.1 - - [26/Jul/2020 23:11:39] "[35m[1mGET / HTTP/1.1[0m" 500 -
26/07/2020 23:11:39  127.0.0.1 - - [26/Jul/2020 23:11:39] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
26/07/2020 23:11:39  127.0.0.1 - - [26/Jul/2020 23:11:39] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
26/07/2020 23:11:39  127.0.0.1 - - [26/Jul/2020 23:11:39] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
26/07/2020 23:11:39  127.0.0.1 - - [26/Jul/2020 23:11:39] "[37mGET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
26/07/2020 23:11:40  127.0.0.1 - - [26/Jul/2020 23:11:40] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 23:11:42  127.0.0.1 - - [26/Jul/2020 23:11:42] "[35m[1mGET / HTTP/1.1[0m" 500 -
26/07/2020 23:11:42  127.0.0.1 - - [26/Jul/2020 23:11:42] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
26/07/2020 23:11:42  127.0.0.1 - - [26/Jul/2020 23:11:42] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
26/07/2020 23:11:42  127.0.0.1 - - [26/Jul/2020 23:11:42] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
26/07/2020 23:11:42  127.0.0.1 - - [26/Jul/2020 23:11:42] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 23:12:13  127.0.0.1 - - [26/Jul/2020 23:12:13] "[35m[1mGET / HTTP/1.1[0m" 500 -
26/07/2020 23:12:14  127.0.0.1 - - [26/Jul/2020 23:12:14] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
26/07/2020 23:12:14  127.0.0.1 - - [26/Jul/2020 23:12:14] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
26/07/2020 23:12:14  127.0.0.1 - - [26/Jul/2020 23:12:14] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
26/07/2020 23:12:14  127.0.0.1 - - [26/Jul/2020 23:12:14] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 23:12:15  127.0.0.1 - - [26/Jul/2020 23:12:15] "[35m[1mGET / HTTP/1.1[0m" 500 -
26/07/2020 23:12:15  127.0.0.1 - - [26/Jul/2020 23:12:15] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
26/07/2020 23:12:15  127.0.0.1 - - [26/Jul/2020 23:12:15] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
26/07/2020 23:12:15  127.0.0.1 - - [26/Jul/2020 23:12:15] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
26/07/2020 23:12:15  127.0.0.1 - - [26/Jul/2020 23:12:15] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
26/07/2020 23:14:24  127.0.0.1 - - [26/Jul/2020 23:14:24] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:14:25  127.0.0.1 - - [26/Jul/2020 23:14:25] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:15:41  127.0.0.1 - - [26/Jul/2020 23:15:41] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:15:41  127.0.0.1 - - [26/Jul/2020 23:15:41] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:15:42  127.0.0.1 - - [26/Jul/2020 23:15:42] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:15:42  127.0.0.1 - - [26/Jul/2020 23:15:42] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:16:41  127.0.0.1 - - [26/Jul/2020 23:16:41] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:16:41  127.0.0.1 - - [26/Jul/2020 23:16:41] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:17:56  127.0.0.1 - - [26/Jul/2020 23:17:56] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:17:59  127.0.0.1 - - [26/Jul/2020 23:17:59] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:20:29  127.0.0.1 - - [26/Jul/2020 23:20:29] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:20:31  127.0.0.1 - - [26/Jul/2020 23:20:31] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:21:45  127.0.0.1 - - [26/Jul/2020 23:21:45] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:21:45  127.0.0.1 - - [26/Jul/2020 23:21:45] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:21:47  127.0.0.1 - - [26/Jul/2020 23:21:47] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:21:47  127.0.0.1 - - [26/Jul/2020 23:21:47] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:21:49  127.0.0.1 - - [26/Jul/2020 23:21:49] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:21:49  127.0.0.1 - - [26/Jul/2020 23:21:49] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
26/07/2020 23:23:36  127.0.0.1 - - [26/Jul/2020 23:23:36] "[37mGET / HTTP/1.1[0m" 200 -
26/07/2020 23:23:36  127.0.0.1 - - [26/Jul/2020 23:23:36] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
27/07/2020 00:06:22  Warnungen: 
27/07/2020 00:06:22   * Running on http://127.0.0.1:1337/ (Press CTRL+C to quit)
27/07/2020 00:06:22   * Restarting with stat
27/07/2020 00:06:22  Warnungen: 
27/07/2020 00:06:22   * Debugger is active!
27/07/2020 00:06:22   * Debugger PIN: 264-486-972
27/07/2020 00:06:34  127.0.0.1 - - [27/Jul/2020 00:06:34] "[37mGET / HTTP/1.1[0m" 200 -
27/07/2020 00:06:34  127.0.0.1 - - [27/Jul/2020 00:06:34] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
27/07/2020 00:06:34  127.0.0.1 - - [27/Jul/2020 00:06:34] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
27/07/2020 00:06:36  127.0.0.1 - - [27/Jul/2020 00:06:36] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:06:37  127.0.0.1 - - [27/Jul/2020 00:06:37] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:06:37  127.0.0.1 - - [27/Jul/2020 00:06:37] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:06:37  127.0.0.1 - - [27/Jul/2020 00:06:37] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:06:37  127.0.0.1 - - [27/Jul/2020 00:06:37] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:06:37  127.0.0.1 - - [27/Jul/2020 00:06:37] "[37mGET /login?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
27/07/2020 00:06:37  127.0.0.1 - - [27/Jul/2020 00:06:37] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:12:27  127.0.0.1 - - [27/Jul/2020 00:12:27] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:12:27  127.0.0.1 - - [27/Jul/2020 00:12:27] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:12:27  127.0.0.1 - - [27/Jul/2020 00:12:27] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:12:27  127.0.0.1 - - [27/Jul/2020 00:12:27] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:12:28  127.0.0.1 - - [27/Jul/2020 00:12:28] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:13:29  127.0.0.1 - - [27/Jul/2020 00:13:29] "[37mGET /index HTTP/1.1[0m" 200 -
27/07/2020 00:13:31  127.0.0.1 - - [27/Jul/2020 00:13:31] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:13:31  127.0.0.1 - - [27/Jul/2020 00:13:31] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:13:31  127.0.0.1 - - [27/Jul/2020 00:13:31] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:13:31  127.0.0.1 - - [27/Jul/2020 00:13:31] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:13:31  127.0.0.1 - - [27/Jul/2020 00:13:31] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:15:34   * Detected change in '/home/aboro72/PycharmProjects/flask-pos/app/routes.py', reloading
27/07/2020 00:15:34   * Restarting with stat
27/07/2020 00:15:35  Warnungen: 
27/07/2020 00:15:35   * Debugger is active!
27/07/2020 00:15:35   * Debugger PIN: 264-486-972
27/07/2020 00:16:00   * Detected change in '/home/aboro72/PycharmProjects/flask-pos/app/routes.py', reloading
27/07/2020 00:16:00   * Restarting with stat
27/07/2020 00:16:01  Warnungen: 
27/07/2020 00:16:01   * Debugger is active!
27/07/2020 00:16:01   * Debugger PIN: 264-486-972
27/07/2020 00:16:02  127.0.0.1 - - [27/Jul/2020 00:16:02] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:16:02  127.0.0.1 - - [27/Jul/2020 00:16:02] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:16:02  127.0.0.1 - - [27/Jul/2020 00:16:02] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:16:02  127.0.0.1 - - [27/Jul/2020 00:16:02] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:16:02  127.0.0.1 - - [27/Jul/2020 00:16:02] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:16:06  127.0.0.1 - - [27/Jul/2020 00:16:06] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:16:06  127.0.0.1 - - [27/Jul/2020 00:16:06] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:16:06  127.0.0.1 - - [27/Jul/2020 00:16:06] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:16:06  127.0.0.1 - - [27/Jul/2020 00:16:06] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:16:06  127.0.0.1 - - [27/Jul/2020 00:16:06] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:19:09   * Detected change in '/home/aboro72/PycharmProjects/flask-pos/app/__init__.py', reloading
27/07/2020 00:19:09   * Restarting with stat
27/07/2020 00:20:01  Warnungen: 
27/07/2020 00:20:01   * Running on http://127.0.0.1:1337/ (Press CTRL+C to quit)
27/07/2020 00:20:01   * Restarting with stat
27/07/2020 00:20:01  Warnungen: 
27/07/2020 00:20:01   * Debugger is active!
27/07/2020 00:20:01   * Debugger PIN: 264-486-972
27/07/2020 00:20:07  127.0.0.1 - - [27/Jul/2020 00:20:07] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:20:07  127.0.0.1 - - [27/Jul/2020 00:20:07] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:20:07  127.0.0.1 - - [27/Jul/2020 00:20:07] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:20:07  127.0.0.1 - - [27/Jul/2020 00:20:07] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:20:08  127.0.0.1 - - [27/Jul/2020 00:20:08] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:21:37   * Detected change in '/home/aboro72/PycharmProjects/flask-pos/app/forms.py', reloading
27/07/2020 00:21:37   * Restarting with stat
27/07/2020 00:21:38  Warnungen: 
27/07/2020 00:21:38   * Debugger is active!
27/07/2020 00:21:38   * Debugger PIN: 264-486-972
27/07/2020 00:24:44  127.0.0.1 - - [27/Jul/2020 00:24:44] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:24:44  127.0.0.1 - - [27/Jul/2020 00:24:44] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:24:44  127.0.0.1 - - [27/Jul/2020 00:24:44] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:24:44  127.0.0.1 - - [27/Jul/2020 00:24:44] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:24:45  127.0.0.1 - - [27/Jul/2020 00:24:45] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:24:46  127.0.0.1 - - [27/Jul/2020 00:24:46] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:24:46  127.0.0.1 - - [27/Jul/2020 00:24:46] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:24:46  127.0.0.1 - - [27/Jul/2020 00:24:46] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:24:46  127.0.0.1 - - [27/Jul/2020 00:24:46] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:24:46  127.0.0.1 - - [27/Jul/2020 00:24:46] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:25:59  127.0.0.1 - - [27/Jul/2020 00:25:59] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:25:59  127.0.0.1 - - [27/Jul/2020 00:25:59] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:26:00  127.0.0.1 - - [27/Jul/2020 00:26:00] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:00  127.0.0.1 - - [27/Jul/2020 00:26:00] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:00  127.0.0.1 - - [27/Jul/2020 00:26:00] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:26:01  127.0.0.1 - - [27/Jul/2020 00:26:01] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:26:02  127.0.0.1 - - [27/Jul/2020 00:26:02] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:26:02  127.0.0.1 - - [27/Jul/2020 00:26:02] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:02  127.0.0.1 - - [27/Jul/2020 00:26:02] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:02  127.0.0.1 - - [27/Jul/2020 00:26:02] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:26:03  127.0.0.1 - - [27/Jul/2020 00:26:03] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:26:03  127.0.0.1 - - [27/Jul/2020 00:26:03] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:03  127.0.0.1 - - [27/Jul/2020 00:26:03] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:26:03  127.0.0.1 - - [27/Jul/2020 00:26:03] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:03  127.0.0.1 - - [27/Jul/2020 00:26:03] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:26:11  Warnungen: 
27/07/2020 00:26:11   * Running on http://127.0.0.1:1337/ (Press CTRL+C to quit)
27/07/2020 00:26:11   * Restarting with stat
27/07/2020 00:26:11  Warnungen: 
27/07/2020 00:26:11   * Debugger is active!
27/07/2020 00:26:11   * Debugger PIN: 264-486-972
27/07/2020 00:26:18  127.0.0.1 - - [27/Jul/2020 00:26:18] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:26:18  127.0.0.1 - - [27/Jul/2020 00:26:18] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:26:18  127.0.0.1 - - [27/Jul/2020 00:26:18] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:18  127.0.0.1 - - [27/Jul/2020 00:26:18] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:18  127.0.0.1 - - [27/Jul/2020 00:26:18] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:26:20  127.0.0.1 - - [27/Jul/2020 00:26:20] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:26:20  127.0.0.1 - - [27/Jul/2020 00:26:20] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:26:20  127.0.0.1 - - [27/Jul/2020 00:26:20] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:20  127.0.0.1 - - [27/Jul/2020 00:26:20] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:21  127.0.0.1 - - [27/Jul/2020 00:26:21] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:26:22  127.0.0.1 - - [27/Jul/2020 00:26:22] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:26:22  127.0.0.1 - - [27/Jul/2020 00:26:22] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:26:22  127.0.0.1 - - [27/Jul/2020 00:26:22] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:22  127.0.0.1 - - [27/Jul/2020 00:26:22] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:22  127.0.0.1 - - [27/Jul/2020 00:26:22] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:26:23  127.0.0.1 - - [27/Jul/2020 00:26:23] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:26:23  127.0.0.1 - - [27/Jul/2020 00:26:23] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:26:23  127.0.0.1 - - [27/Jul/2020 00:26:23] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:23  127.0.0.1 - - [27/Jul/2020 00:26:23] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:24  127.0.0.1 - - [27/Jul/2020 00:26:24] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:26:25  127.0.0.1 - - [27/Jul/2020 00:26:25] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:26:25  127.0.0.1 - - [27/Jul/2020 00:26:25] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:25  127.0.0.1 - - [27/Jul/2020 00:26:25] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:26:25  127.0.0.1 - - [27/Jul/2020 00:26:25] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:25  127.0.0.1 - - [27/Jul/2020 00:26:25] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:26:26  127.0.0.1 - - [27/Jul/2020 00:26:26] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:26:26  127.0.0.1 - - [27/Jul/2020 00:26:26] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:26  127.0.0.1 - - [27/Jul/2020 00:26:26] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:26:26  127.0.0.1 - - [27/Jul/2020 00:26:26] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:26  127.0.0.1 - - [27/Jul/2020 00:26:26] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:26:28  127.0.0.1 - - [27/Jul/2020 00:26:28] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:26:28  127.0.0.1 - - [27/Jul/2020 00:26:28] "[37mGET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:28  127.0.0.1 - - [27/Jul/2020 00:26:28] "[37mGET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
27/07/2020 00:26:28  127.0.0.1 - - [27/Jul/2020 00:26:28] "[37mGET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
27/07/2020 00:26:28  127.0.0.1 - - [27/Jul/2020 00:26:28] "[37mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
27/07/2020 00:26:32   * To enable the debugger you need to enter the security pin:
27/07/2020 00:26:32   * Debugger pin code: 264-486-972
27/07/2020 00:26:32  127.0.0.1 - - [27/Jul/2020 00:26:32] "[37mGET /login?__debugger__=yes&cmd=printpin&s=mS4dTaK7KgzoOlNrHbNy HTTP/1.1[0m" 200 -
27/07/2020 00:27:35  127.0.0.1 - - [27/Jul/2020 00:27:35] "[37mGET /login?__debugger__=yes&cmd=pinauth&pin=264-486-972&s=mS4dTaK7KgzoOlNrHbNy HTTP/1.1[0m" 200 -
27/07/2020 00:28:47  Warnungen: 
27/07/2020 00:28:47   * Running on http://127.0.0.1:1337/ (Press CTRL+C to quit)
27/07/2020 00:28:53  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    form = LoginForm()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:28:53  127.0.0.1 - - [27/Jul/2020 00:28:53] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:28:55  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    form = LoginForm()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:28:55  127.0.0.1 - - [27/Jul/2020 00:28:55] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:28:58  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    form = LoginForm()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:28:58  127.0.0.1 - - [27/Jul/2020 00:28:58] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:33:12  127.0.0.1 - - [27/Jul/2020 00:33:12] "[37mGET /index HTTP/1.1[0m" 200 -
27/07/2020 00:33:12  127.0.0.1 - - [27/Jul/2020 00:33:12] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
27/07/2020 00:33:16  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    form = LoginForm()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:33:16  127.0.0.1 - - [27/Jul/2020 00:33:16] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:33:20  127.0.0.1 - - [27/Jul/2020 00:33:20] "[37mGET /index HTTP/1.1[0m" 200 -
27/07/2020 00:35:03  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    form = LoginForm()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:35:03  127.0.0.1 - - [27/Jul/2020 00:35:03] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:35:05  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    form = LoginForm()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:35:05  127.0.0.1 - - [27/Jul/2020 00:35:05] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:35:06  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    form = LoginForm()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:35:06  127.0.0.1 - - [27/Jul/2020 00:35:06] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:40:08  127.0.0.1 - - [27/Jul/2020 00:40:08] "[37mGET /index HTTP/1.1[0m" 200 -
27/07/2020 00:40:09  127.0.0.1 - - [27/Jul/2020 00:40:09] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
27/07/2020 00:40:12  127.0.0.1 - - [27/Jul/2020 00:40:12] "[37mGET /index HTTP/1.1[0m" 200 -
27/07/2020 00:40:12  127.0.0.1 - - [27/Jul/2020 00:40:12] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
27/07/2020 00:40:13  127.0.0.1 - - [27/Jul/2020 00:40:13] "[37mGET /index HTTP/1.1[0m" 200 -
27/07/2020 00:40:13  127.0.0.1 - - [27/Jul/2020 00:40:13] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
27/07/2020 00:40:15  127.0.0.1 - - [27/Jul/2020 00:40:15] "[37mGET /index HTTP/1.1[0m" 200 -
27/07/2020 00:40:29  Warnungen: 
27/07/2020 00:40:29   * Running on http://127.0.0.1:1337/ (Press CTRL+C to quit)
27/07/2020 00:40:34  Exception on /index [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 19, in index
    return render_template('index.html', title='Home', user=user, posts=posts)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 7, in block "content"
    <p class="lead">{{ post.author.username }} says: <b>{{ post.body }}</b></p>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'author'
27/07/2020 00:40:34  127.0.0.1 - - [27/Jul/2020 00:40:34] "[35m[1mGET /index HTTP/1.1[0m" 500 -
27/07/2020 00:40:36  Exception on /index [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 19, in index
    return render_template('index.html', title='Home', user=user, posts=posts)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 7, in block "content"
    <p class="lead">{{ post.author.username }} says: <b>{{ post.body }}</b></p>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'author'
27/07/2020 00:40:36  127.0.0.1 - - [27/Jul/2020 00:40:36] "[35m[1mGET /index HTTP/1.1[0m" 500 -
27/07/2020 00:40:37  Exception on /index [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 19, in index
    return render_template('index.html', title='Home', user=user, posts=posts)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 7, in block "content"
    <p class="lead">{{ post.author.username }} says: <b>{{ post.body }}</b></p>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'author'
27/07/2020 00:40:37  127.0.0.1 - - [27/Jul/2020 00:40:37] "[35m[1mGET /index HTTP/1.1[0m" 500 -
27/07/2020 00:40:38  Exception on /index [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 19, in index
    return render_template('index.html', title='Home', user=user, posts=posts)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 7, in block "content"
    <p class="lead">{{ post.author.username }} says: <b>{{ post.body }}</b></p>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'author'
27/07/2020 00:40:38  127.0.0.1 - - [27/Jul/2020 00:40:38] "[35m[1mGET /index HTTP/1.1[0m" 500 -
27/07/2020 00:40:39  Exception on /index [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 19, in index
    return render_template('index.html', title='Home', user=user, posts=posts)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 7, in block "content"
    <p class="lead">{{ post.author.username }} says: <b>{{ post.body }}</b></p>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'author'
27/07/2020 00:40:39  127.0.0.1 - - [27/Jul/2020 00:40:39] "[35m[1mGET /index HTTP/1.1[0m" 500 -
27/07/2020 00:42:46  Exception on /index [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 19, in index
    ]
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 7, in block "content"
    <p class="lead">{{ post.author.username }} says: <b>{{ post.body }}</b></p>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'author'
27/07/2020 00:42:46  127.0.0.1 - - [27/Jul/2020 00:42:46] "[35m[1mGET /index HTTP/1.1[0m" 500 -
27/07/2020 00:42:47  Exception on /index [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 19, in index
    ]
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 7, in block "content"
    <p class="lead">{{ post.author.username }} says: <b>{{ post.body }}</b></p>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'author'
27/07/2020 00:42:47  127.0.0.1 - - [27/Jul/2020 00:42:47] "[35m[1mGET /index HTTP/1.1[0m" 500 -
27/07/2020 00:42:48  Exception on /index [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 19, in index
    ]
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 7, in block "content"
    <p class="lead">{{ post.author.username }} says: <b>{{ post.body }}</b></p>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'author'
27/07/2020 00:42:48  127.0.0.1 - - [27/Jul/2020 00:42:48] "[35m[1mGET /index HTTP/1.1[0m" 500 -
27/07/2020 00:42:53  Exception on /index [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 19, in index
    ]
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/index.html", line 7, in block "content"
    <p class="lead">{{ post.author.username }} says: <b>{{ post.body }}</b></p>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'author'
27/07/2020 00:42:53  127.0.0.1 - - [27/Jul/2020 00:42:53] "[35m[1mGET /index HTTP/1.1[0m" 500 -
27/07/2020 00:43:07  Warnungen: 
27/07/2020 00:43:07   * Running on http://127.0.0.1:1337/ (Press CTRL+C to quit)
27/07/2020 00:43:11  127.0.0.1 - - [27/Jul/2020 00:43:11] "[37mGET /index HTTP/1.1[0m" 200 -
27/07/2020 00:43:11  127.0.0.1 - - [27/Jul/2020 00:43:11] "[36mGET /static/styles/cover.css HTTP/1.1[0m" 304 -
27/07/2020 00:43:21  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    form = LoginForm()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:43:21  127.0.0.1 - - [27/Jul/2020 00:43:21] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:43:28  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    form = LoginForm()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:43:28  127.0.0.1 - - [27/Jul/2020 00:43:28] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:45:26  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    form = LoginForm()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:45:26  127.0.0.1 - - [27/Jul/2020 00:45:26] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:45:28  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    form = LoginForm()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:45:28  127.0.0.1 - - [27/Jul/2020 00:45:28] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:46:42  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:46:42  127.0.0.1 - - [27/Jul/2020 00:46:42] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:46:43  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
27/07/2020 00:46:43  127.0.0.1 - - [27/Jul/2020 00:46:43] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:47:11  Warnungen: 
27/07/2020 00:47:11   * Running on http://127.0.0.1:1337/ (Press CTRL+C to quit)
27/07/2020 00:47:15  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
27/07/2020 00:47:15  127.0.0.1 - - [27/Jul/2020 00:47:15] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:47:17  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
27/07/2020 00:47:17  127.0.0.1 - - [27/Jul/2020 00:47:17] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:47:18  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
27/07/2020 00:47:18  127.0.0.1 - - [27/Jul/2020 00:47:18] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:47:20  127.0.0.1 - - [27/Jul/2020 00:47:20] "[37mGET /index HTTP/1.1[0m" 200 -
27/07/2020 00:47:22  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
27/07/2020 00:47:22  127.0.0.1 - - [27/Jul/2020 00:47:22] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:47:57  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 7, in block "content"
    </main>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
27/07/2020 00:47:57  127.0.0.1 - - [27/Jul/2020 00:47:57] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:47:59  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 7, in block "content"
    </main>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
27/07/2020 00:47:59  127.0.0.1 - - [27/Jul/2020 00:47:59] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:48:00  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 7, in block "content"
    </main>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
27/07/2020 00:48:00  127.0.0.1 - - [27/Jul/2020 00:48:00] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:48:02  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 7, in block "content"
    </main>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
27/07/2020 00:48:02  127.0.0.1 - - [27/Jul/2020 00:48:02] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:48:03  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 7, in block "content"
    </main>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
27/07/2020 00:48:03  127.0.0.1 - - [27/Jul/2020 00:48:03] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:48:03  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 7, in block "content"
    </main>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
27/07/2020 00:48:03  127.0.0.1 - - [27/Jul/2020 00:48:03] "[35m[1mGET /login HTTP/1.1[0m" 500 -
27/07/2020 00:48:04  Exception on /login [GET]
Traceback (most recent call last):
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aboro72/PycharmProjects/flask-pos/app/routes.py", line 25, in login
    return render_template('login.html', title='Sign In')
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/base.html", line 46, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aboro72/PycharmProjects/flask-pos/app/templates/login.html", line 7, in block "content"
    </main>
  File "/home/aboro72/PycharmProjects/flask-pos/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
27/07/2020 00:48:04  127.0.0.1 - - [27/Jul/2020 00:48:04] "[35m[1mGET /login HTTP/1.1[0m" 500 -
28/07/2020 01:24:07  Warnungen: 
28/07/2020 01:24:07   * Running on http://127.0.0.1:1337/ (Press CTRL+C to quit)
